set(CONFIG_APP_VERSION_MAJOR 1)
set(CONFIG_APP_VERSION_MINOR 0)
set(CONFIG_APP_VERSION_REVISION 0)
set(CONFIG_APP_VERSION_SUFIX "-RC1-${TARGET_SLOT}")
set(CONFIG_RFM_TEST_ENABLED 1)

if(CMAKE_BUILD_TYPE STREQUAL "release")
    set(CONFIG_APP_MINIMAL 1) 
endif()
