# Platform configuration
add_definitions(-DSTM32L073xx)
set(CONFIG_PLAT_SLOT_INFO_SECTION_SIZE 256)
add_definitions(-DCONFIG_PLAT_SLOT_INFO_SECTION_SIZE=${CONFIG_PLAT_SLOT_INFO_SECTION_SIZE})
set(CONFIG_PLAT_SLOT_INFO_MAGIC_VALUE 0xAA55AA55)
add_definitions(-DCONFIG_PLAT_SLOT_INFO_MAGIC_VALUE=${CONFIG_PLAT_SLOT_INFO_MAGIC_VALUE})
set(CONFIG_PLAT_SLOT_BOOT_ADDR 0x08000000)
set(CONFIG_PLAT_SLOT_A_ADDR 0x08010000)
set(CONFIG_PLAT_SLOT_B_ADDR 0x08020800)

include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)

# Get build time
execute_process(
    COMMAND bash -c "date"
    OUTPUT_VARIABLE PLAT_BUILD_TIME
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get git branch
execute_process(
    COMMAND bash -c "git rev-parse --abbrev-ref HEAD"
    OUTPUT_VARIABLE PLAT_GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get git hash
execute_process(
    COMMAND bash -c "git rev-parse HEAD"
    OUTPUT_VARIABLE PLAT_GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Create .bin
add_custom_target(${PROJECT_NAME}.${TARGET_SLOT}.bin ALL DEPENDS ${PROJECT_NAME}
    COMMAND ${CMAKE_OBJCOPY} -v -O binary ${CMAKE_BINARY_DIR}/apps/${TARGET_APP}/${PROJECT_NAME}.${TARGET_SLOT}.elf ${PROJECT_NAME}.${TARGET_SLOT}.bin)

if(${PROJECT_NAME} STREQUAL "main")
    # Fullfill the binary with meta
    add_custom_target(${PROJECT_NAME}.${TARGET_SLOT}.bin.meta ALL DEPENDS ${PROJECT_NAME}
        COMMAND python3 ${CMAKE_CURRENT_LIST_DIR}/meta.py ${CMAKE_BINARY_DIR}/${PROJECT_NAME}.${TARGET_SLOT}.bin ${CONFIG_PLAT_SLOT_INFO_SECTION_SIZE})
endif()