# Platform configuration
set(CONFIG_PLAT_INFO_SECTION_SIZE 0x100)
add_definitions(-DCONFIG_PLAT_INFO_SECTION_SIZE=${CONFIG_PLAT_INFO_SECTION_SIZE})
set(CONFIG_PLAT_SLOT_BOOT_ADDR 0x08000000)
set(CONFIG_PLAT_SLOT_A_ADDR 0x08010000)
set(CONFIG_PLAT_SLOT_B_ADDR 0x08020000)

# EGL platfrom info configuration
add_definitions(-DCONFIG_EGL_PLAT_INFO_VERSION_SUFIX_BUFF_SIZE=8)
add_definitions(-DCONFIG_EGL_PLAT_INFO_GIT_BRANCH_SUFIX_BUFF_SIZE=32)
add_definitions(-DCONFIG_EGL_PLAT_INFO_GIT_HASH_SUFIX_BUFF_SIZE=41)
add_definitions(-DCONFIG_EGL_PLAT_INFO_NAME_BUFF_SIZE=32)
add_definitions(-DCONFIG_EGL_PLAT_INFO_BUILDTIME_BUFF_SIZE=64)

include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)

# Get build time
execute_process(
    COMMAND bash -c "date"
    OUTPUT_VARIABLE PLAT_BUILD_TIME
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get git branch
execute_process(
    COMMAND bash -c "git rev-parse --abbrev-ref HEAD"
    OUTPUT_VARIABLE PLAT_GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get git hash
execute_process(
    COMMAND bash -c "git rev-parse HEAD"
    OUTPUT_VARIABLE PLAT_GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

configure_file(${CMAKE_CURRENT_LIST_DIR}/plat_info.c.in ${CMAKE_BINARY_DIR}/plat_info.c @ONLY)