name: Build All Targets

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARMGCC_DIR : "/usr"

    strategy:
      matrix:
        build_type: [debug, release]
        target_app: [blink, radio_switch, rfm_test]

    steps:
      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install crcmod

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Config
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DTARGET_APP=${{matrix.target_app}} \
                -DTARGET_PLATFORM=stm32l073-nucleo \
                -DTARGET_SLOT=boot \
                -DTARGET_RFM=rfm69 \
                -DCMAKE_TOOLCHAIN_FILE=./plat/stm32l073-nucleo/toolchain.cmake \
                -S ./ \
                -B ./build/${{matrix.target_app}} \
                --build ./build/${{matrix.target_app}} \
                --target all

      - name: Build
        run: |
            cmake --build ./build/${{matrix.target_app}} --target all