name: Build All Targets

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARMGCC_DIR : "/usr"

    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build blink-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}
        run: |
          cmake --preset blink-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}
          cmake --build --preset blink-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}

      - name: Build blink-stm32l073-nucleo-slot-a-${{ matrix.build_type }}
        run: |
          cmake --preset blink-stm32l073-nucleo-slot-a-${{ matrix.build_type }}
          cmake --build --preset blink-stm32l073-nucleo-slot-a-${{ matrix.build_type }}

      - name: Build blink-stm32l073-nucleo-slot-b-${{ matrix.build_type }}
        run: |
          cmake --preset blink-stm32l073-nucleo-slot-b-${{ matrix.build_type }}
          cmake --build --preset blink-stm32l073-nucleo-slot-b-${{ matrix.build_type }}

      - name: Build rfm-test-stm32l073-nucleo-${{ matrix.build_type }}
        run: |
          cmake --preset rfm-test-stm32l073-nucleo-${{ matrix.build_type }}
          cmake --build --preset rfm-test-stm32l073-nucleo-${{ matrix.build_type }}

      - name: Build radio-switch-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}
        run: |
          cmake --preset radio-switch-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}
          cmake --build --preset radio-switch-stm32l073-nucleo-slot-boot-${{ matrix.build_type }}

