#ifndef TX_USER_H
#define TX_USER_H

#define TX_DISABLE_REDUNDANT_CLEARING
#define TX_DISABLE_NOTIFY_CALLBACKS
#define TX_TIMER_THREAD_STACK_SIZE (1024U)
// #define TX_ENABLE_STACK_CHECKING
#define TX_NO_FILEX_POINTER

#endif